2023-12-02 10:00:41.168 | ERROR    | ai_translate:run:46 - An error occurred during translation: Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-BvbTW***************************************DdC1. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
2023-12-02 10:02:22.746 | ERROR    | ai_translate:run:46 - An error occurred during translation: Completions.create() got an unexpected keyword argument 'OPENAI_API_BASE'
2023-12-02 10:03:49.071 | ERROR    | ai_translate:run:46 - An error occurred during translation: 'str' object has no attribute 'dict'
2023-12-02 13:09:27.518 | ERROR    | doc_analyze.doc_analyze:run:16 - An error occurred during translation: Connection error.
2023-12-02 13:32:03.970 | ERROR    | doc_analyze.doc_analyze:run:16 - An error occurred during translation: Connection error.
2023-12-02 15:00:48.398 | ERROR    | ai_translate:run:46 - An error occurred during translation: 'str' object has no attribute 'dict'
2023-12-02 15:36:55.713 | ERROR    | doc_analyze.doc_analyze:run:16 - An error occurred during translation: Connection error.
2023-12-02 15:40:58.414 | ERROR    | doc_analyze.doc_analyze:run:16 - An error occurred during translation: Connection error.
